### ISSUE TITLE
Pyinstaller missing sampling_rule.json

### ISSUE THREAD

**Issue by abivolmv** [aws/aws-xray-sdk-python#105]
Hi,
when packaging custom python app that imports this sdk :
```
from aws_xray_sdk.core import xray_recorder
```
it runs successfully but when trying to execute the packaged app I get this error :
```
C:\Users\abivol\repos\surreal-queue-dispatcher\dist\message_dispatcher>message_dispatcher.exe
Traceback (most recent call last):
  File "run_surreal.py", line 13, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "surreal\surreal.py", line 18, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\aws_xray_sdk\core\__init__.py", line 1, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\aws_xray_sdk\core\recorder.py", line 16, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\aws_xray_sdk\core\sampling\sampler.py", line 6, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\aws_xray_sdk\core\sampling\local\sampler.py", line 9, in <module>
IOError: [Errno 2] No such file or directory: 'C:\\Users\\abivol\\repos\\SURREA~1\\dist\\MESSAG~1\\aws_xray_sdk\\core\\sampling\\local\\samp
ling_rule.json'
[1384] Failed to execute script run_surreal
```

The only warning I get about xray when building with debug mode on is :
```
invalid module named aws_xray_sdk.core.async_recorder - imported by aws_xray_sdk.core (conditional)
```

Pyinstaller 3.4
Python 2.7.15
`pyinstaller --log-level=DEBUG --onedir -y -p ./ surreal.spec`
and spec file attached
[warn-surreal.txt](https://github.com/aws/aws-xray-sdk-python/files/2450872/warn-surreal.txt)

**Comment by haotianw465** [comment]
Hi, the SDK use https://github.com/aws/aws-xray-sdk-python/blob/master/MANIFEST.in to specify extras file to include in the package (in this case they are `.json` files). It looks like `PyInstaller` has some similar functions https://pyinstaller.readthedocs.io/en/stable/spec-files.html#adding-data-files. Please let me know if this helps.

**Comment by abivolmv** [comment]
Yes, thanks! That helped. I ended up using collect :
```
needed_aws_xray_sdk_files = [(r'aws_xray_sdk\core\sampling\local\sampling_rule.json',
                           r'C:\Users\abivol\repos\surreal-queue-dispatcher\venv\Lib\site-packages\aws_xray_sdk\core\sampling\local\sampling_rule.json',
                          'DATA')]
...
coll = COLLECT(exe,
               a.binaries,
               needed_aws_xray_sdk_files,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='message_dispatcher')
```

**Comment by christianbeland** [comment]
I understand you can add it... but it doesn't leave you the choice to not rely on this file. Even if the LocalSampler is not used, since it is imported in xray_recorder, it will automatically load the sampling_rule.json file.

Would it be possible to only load this file if the LocalSampler is initialized? 

Moving 

`with open(resource_filename(__name__, 'sampling_rule.json')) as f:
    local_sampling_rule = json.load(f)
`
to __init__
