### ISSUE TITLE
The jsonpickle dependency can cause issues when using the AWS Lambda runtime with the Serverless framework

### ISSUE THREAD

**Issue by affablebloke** [aws/aws-xray-sdk-python#220]
**Issue:**

Since the jsonpickle library is not version pinned, it pulls the latest version which is [jsonpickle==1.4](https://pypi.org/project/jsonpickle/#history). If you're using the serverless framework with the plugin [serverless-python-requirements](https://github.com/UnitedIncome/serverless-python-requirements#slim-package) and setting the property [`slim: true`](https://github.com/UnitedIncome/serverless-python-requirements#slim-package) will cause the aws-xray-sdk to crash upon instantiating. 

**Stack trace:**

```bash
[ERROR] PackageNotFoundError: importlib_metadata
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/handler.py", line 12, in <module>
    from aws_xray_sdk.core import patch_all, xray_recorder
  File "/var/task/aws_xray_sdk/core/__init__.py", line 1, in <module>
    from .recorder import AWSXRayRecorder
  File "/var/task/aws_xray_sdk/core/recorder.py", line 10, in <module>
    from .models.segment import Segment, SegmentContextManager
  File "/var/task/aws_xray_sdk/core/models/segment.py", line 4, in <module>
    from .entity import Entity
  File "/var/task/aws_xray_sdk/core/models/entity.py", line 7, in <module>
    import jsonpickle
  File "/var/task/jsonpickle/__init__.py", line 64, in <module>
    from .version import __version__  # noqa: F401
  File "/var/task/jsonpickle/version.py", line 2, in <module>
    import importlib_metadata as metadata
  File "/var/task/importlib_metadata/__init__.py", line 602, in <module>
    __version__ = version(__name__)
  File "/var/task/importlib_metadata/__init__.py", line 564, in version
    return distribution(distribution_name).version
  File "/var/task/importlib_metadata/__init__.py", line 537, in distribution
    return Distribution.from_name(distribution_name)
  File "/var/task/importlib_metadata/__init__.py", line 205, in from_name
    raise PackageNotFoundError(name)
```

**Solution:**

Version pin aws-xray-sdk's setup.py to jsonpickle==1.3.0, I doubt this library depends on 1.4.0 features, I could be wrong?

For now, I'm overriding our project's requirements.txt to use jsonpickle==1.3.0 or you can tell python-serverless-requirements to [not strip out the `dist-info` directories](https://github.com/UnitedIncome/serverless-python-requirements#custom-removal-patterns).

**Comment by srprash** [comment]
Hi @affablebloke 
Extremely sorry that we missed to address this issue. Looking at it now the `[ERROR] PackageNotFoundError: importlib_metadata` was caused in the jsonpickle 1.4.0 and was promptly fixed in [1.4.1](https://github.com/jsonpickle/jsonpickle/blob/master/CHANGES.rst#v141). So this shouldn't be a problem with the X-Ray SDK anymore.

I'm not quite sure if version pinning the dependencies is a good idea because a strict version pinning (jsonpickle==1.3.0 for example) has a few potential problems. Firstly, it could prevent the users of the SDK to upgrade the jsonpickle dependency further. Secondly, for any future releases of the dependency with security issues or bug fixes will require an upgrade in the SDK and a new release.

I think at this point, not pinning the versions works fine and I we will fix any issue arising in the SDK due to new dependency versions as quickly as possible.

Thanks!
