### ISSUE TITLE
aws-xray-sdk-python has actual dependance on module "requests" but not declared via pip install

### ISSUE THREAD

**Issue by FireballDWF** [aws/aws-xray-sdk-python#224]
In an environment with botocore-1.15.49 installed without the "requests" module installed, installing aws-xray-sdk via pip does not result in the module "requests" being installed despite the dependency which can be seen in the provided traceback.  Suspect that it's due to https://aws.amazon.com/blogs/developer/removing-the-vendored-version-of-requests-from-botocore/

```
$ pip3 install aws_xray_sdk
Collecting aws_xray_sdk
  Downloading aws_xray_sdk-2.5.0-py2.py3-none-any.whl (94 kB)
     |████████████████████████████████| 94 kB 838 kB/s 
Collecting jsonpickle
  Downloading jsonpickle-1.4.1-py2.py3-none-any.whl (36 kB)
Collecting future
  Using cached future-0.18.2.tar.gz (829 kB)
Collecting wrapt
  Downloading wrapt-1.12.1.tar.gz (27 kB)
Requirement already satisfied: botocore>=1.11.3 in /Users/filiatra/Library/Python/3.8/lib/python/site-packages (from aws_xray_sdk) (1.16.5)
Requirement already satisfied: importlib-metadata in /Users/filiatra/Library/Python/3.8/lib/python/site-packages (from jsonpickle->aws_xray_sdk) (1.6.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /Users/filiatra/Library/Python/3.8/lib/python/site-packages (from botocore>=1.11.3->aws_xray_sdk) (2.8.1)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /Users/filiatra/Library/Python/3.8/lib/python/site-packages (from botocore>=1.11.3->aws_xray_sdk) (0.9.5)
Requirement already satisfied: urllib3<1.26,>=1.20; python_version != "3.4" in /Users/filiatra/Library/Python/3.8/lib/python/site-packages (from botocore>=1.11.3->aws_xray_sdk) (1.25.9)
Requirement already satisfied: docutils<0.16,>=0.10 in /Users/filiatra/Library/Python/3.8/lib/python/site-packages (from botocore>=1.11.3->aws_xray_sdk) (0.15.2)
Requirement already satisfied: zipp>=0.5 in /Users/filiatra/Library/Python/3.8/lib/python/site-packages (from importlib-metadata->jsonpickle->aws_xray_sdk) (3.1.0)
Requirement already satisfied: six>=1.5 in /Users/filiatra/Library/Python/3.8/lib/python/site-packages (from python-dateutil<3.0.0,>=2.1->botocore>=1.11.3->aws_xray_sdk) (1.14.0)
Building wheels for collected packages: future, wrapt
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=7e241fa16b02bf14aac42023ca2a8c332c4592b3021a75b60ddf93a6e91b274c
  Stored in directory: /Users/filiatra/Library/Caches/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4
  Building wheel for wrapt (setup.py) ... done
  Created wheel for wrapt: filename=wrapt-1.12.1-cp38-cp38-macosx_10_15_x86_64.whl size=32613 sha256=4573a70defc7c0e81f49e880bc136e3d447625209db87b1c92b1b8b53b92cb2d
  Stored in directory: /Users/filiatra/Library/Caches/pip/wheels/5f/fd/9e/b6cf5890494cb8ef0b5eaff72e5d55a70fb56316007d6dfe73
Successfully built future wrapt
Installing collected packages: jsonpickle, future, wrapt, aws-xray-sdk
Successfully installed aws-xray-sdk-2.5.0 future-0.18.2 jsonpickle-1.4.1 wrapt-1.12.1
```
```
2020-05-09 16:18:19,736: aws_xray_sdk.core.patcher:INFO successfully patched module botocore
Traceback (most recent call last):
  File "/usr/local/bin/custodian", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/c7n/cli.py", line 359, in main
    command(config)
  File "/usr/local/lib/python3.8/site-packages/c7n/commands.py", line 106, in _load_policies
    p_options = provider.initialize(options)
  File "/usr/local/lib/python3.8/site-packages/c7n/resources/aws.py", line 578, in initialize
    XrayTracer.initialize(utils.parse_url_config(options.tracer))
  File "/usr/local/lib/python3.8/site-packages/c7n/resources/aws.py", line 400, in initialize
    patch(['boto3', 'requests'])
  File "/usr/local/lib/python3.8/site-packages/aws_xray_sdk/core/patcher.py", line 98, in patch
    _patch_module(m, raise_errors)
  File "/usr/local/lib/python3.8/site-packages/aws_xray_sdk/core/patcher.py", line 107, in _patch_module
    _patch(module_to_patch)
  File "/usr/local/lib/python3.8/site-packages/aws_xray_sdk/core/patcher.py", line 123, in _patch
    imported_module.patch()
  File "/usr/local/lib/python3.8/site-packages/aws_xray_sdk/ext/requests/patch.py", line 10, in patch
    wrapt.wrap_function_wrapper(
  File "/usr/local/lib/python3.8/site-packages/wrapt/wrappers.py", line 831, in wrap_function_wrapper
    return wrap_object(module, name, FunctionWrapper, (wrapper,))
  File "/usr/local/lib/python3.8/site-packages/wrapt/wrappers.py", line 777, in wrap_object
    (parent, attribute, original) = resolve_path(module, name)
  File "/usr/local/lib/python3.8/site-packages/wrapt/wrappers.py", line 734, in resolve_path
    __import__(module)
ModuleNotFoundError: No module named 'requests'
```

**Comment by bhautikpip** [comment]
Hi @FireballDWF ,

Are you having this error while patching botocore ? And are you suggesting to include `import requests` in setup.py (https://github.com/aws/aws-xray-sdk-python/blob/master/setup.py#L46) as it is a dependency for `botocore` module ?

**Comment by FireballDWF** [comment]
Q1: No
Q2: Yes, except that the reason is that line 10-11 of aws_xray_sdk/ext/requests/patch.py explicitly instructs the patching of requests.  botocore no longer depends on nor vends the request module per the referenced url in my original report

**Comment by bhautikpip** [comment]
Hi @FireballDWF ,

I see. Thanks for pointing this out. I would really appreciate PR!

**Comment by srprash** [comment]
Hi @FireballDWF The aws-xray-sdk itself doesn't depend on the requests library for any of its workings. So I don't believe it needs to be included in the setup.py of the SDK project.
Also, the third-party libraries which the SDK supports patching for need to be installed separately by the users depending on their use case. Otherwise, the user will get the `ModuleNotFoundError` for any of the patched libraries which are not already installed.

Closing this issues. Please feel free to re-open if you still have any troubles. Thanks!
