### ISSUE TITLE
X-Ray is not being disabled when AWS_XRAY_SDK_ENABLED is 'false'

### ISSUE THREAD

**Issue by dgard1981** [aws/aws-xray-sdk-python#330]
I'm using `pytest` to run some unit tests, so I wish to disable the X-Ray SDK. To do this I'm setting an environment variable -

```python
export AWS_XRAY_SDK_ENABLED=false
```

However, X-Ray is still running and my tests are failing. The traceback shows that the error originates in my logging module, when I add a subsegment. However, the line prior to that I am outputting the value of the environment variable `AWS_XRAY_SDK_ENABLED`, and it's value is always `false`.

Is there something more that must be done to disable the X-Ray SDK? Or is there some sort of bug that may be causing me issues?

I'm running using the following -
* Python: 3.9
* aws-xray-sdk: 2.4.3

---

#### Traceback

```shell
Traceback (most recent call last):
  File "/home/usrname/myproject/myfunction/proxy/app.py", line 44, in lambda_handler
    add_xray_subsegment('functionresult', annotations, exception)
  File "/home/usrname/myproject/myfunction/proxy/core/logging.py", line 22, in add_xray_subsegment
    with xray_recorder.capture(name) as subsegment:
  File "/home/usrname/.local/lib/python3.8/site-packages/aws_xray_sdk/core/models/subsegment.py", line 62, in __enter__
    self.subsegment = self.recorder.begin_subsegment(
  File "/home/usrname/.local/lib/python3.8/site-packages/aws_xray_sdk/core/recorder.py", line 292, in begin_subsegment
    segment = self.current_segment()
  File "/home/usrname/.local/lib/python3.8/site-packages/aws_xray_sdk/core/recorder.py", line 270, in current_segment
    entity = self.get_trace_entity()
  File "/home/usrname/.local/lib/python3.8/site-packages/aws_xray_sdk/core/recorder.py", line 390, in get_trace_entity
    return self.context.get_trace_entity()
  File "/home/usrname/.local/lib/python3.8/site-packages/aws_xray_sdk/core/context.py", line 99, in get_trace_entity
    return self.handle_context_missing()
  File "/home/usrname/.local/lib/python3.8/site-packages/aws_xray_sdk/core/context.py", line 123, in handle_context_missing
    raise SegmentNotFoundException(MISSING_SEGMENT_MSG)
aws_xray_sdk.core.exceptions.exceptions.SegmentNotFoundException: cannot find the current segment/subsegment, please make sure you have a segment open
```

**Comment by srprash** [comment]
Hi @dgard1981 
Thanks for providing detailed description of the issue. From the traceback logs, it seems like you're running on Lambda. Is it true?
I haven't tried disabling X-Ray SDK on lambda via the environment variable, so can't say if it works or not.
Have you tried running this code locally in a non-lambda environment? Does it work there?

**Comment by dgard1981** [comment]
Hi @srprash, thanks for your reply.

I have done a little more testing, so let me update you... When running locally, everything seems to be working as it should. I am able to run my code with X-Ray disabled in the following scenarios.
   - When invoking the Lambda locally using `sam local invoke`
   - When running the Lambda locally using `sam local start-lambda`, and invoking the function through the AWS CLI or Python SDK.
   - When testing using `python -m pytest test/unit`, where `AWS_XRAY_SDK_ENABLED` is set to `false` in 'pytest.ini'.
   - When calling the `lambda_handler` function in 'app.py' directly, where `AWS_XRAY_SDK_ENABLED` is set to `false` in using an exported global variable.

The issue seems to only occur when running unit tests in AWS CodeBuild. For some reason, the global variable does not seem to be honoured. I can see from the output that 'pytest.ini' is being used as the config file, and that the value of `AWS_XRAY_SDK_ENABLED` is `false`. I have also tried adding `export AWS_XRAY_SDK_ENABLED=false` directly before the tests are run, but that doesn't work either.

I'm no expert with CodeBuild, so I'm going to do some reading around how that handles global variables, but if you have any thoughts about what the issue may be based on what I've shared I'd be grateful.

**Comment by dgard1981** [comment]
I finally found a solution to this issue.

Somehow my local version of `aws-xray-sdk` had been updated to **v2.9.0**, which was beyond **v2.4.3** as specified in requirements.txt. I found [this response](https://github.com/aws/aws-xray-sdk-python/issues/155#issuecomment-624618451) in a GitHub issue that was similar to my own, which said that the problem was solved in **v2.5.0**, and hey-presto, updating requirements.txt did the job.
