### ISSUE TITLE
Error when using AsyncContext in python 3.11.5

### ISSUE THREAD

**Issue by JoJoJoJoJoJoJo** [aws/aws-xray-sdk-python#417]
Hi when I'm trying to use AsyncContext with python 3.11.5, an error is raised.
I found a similar issue below so I believe it's associated with python version.

## Code
```
from fastapi import FastAPI
import random
import time
import asyncio
from aws_xray_sdk.core.async_context import AsyncContext
from aws_xray_sdk.core import xray_recorder

xray_recorder.configure('app', context=AsyncContext())

app = FastAPI()

@app.get('/test')
def test():
    print('test called')
    time.sleep(random.randint(1, 3))
    return {'hello': 'test'}
```
## Full Error Stack

```
/opt/homebrew/Caskroom/miniconda/base/envs/fastapi/lib/python3.11/site-packages/uvicorn/lifespan/on.py:49: RuntimeWarning: coroutine 'LifespanOn.main' was never awaited
  main_lifespan_task = loop.create_task(self.main())  # noqa: F841
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/fastapi/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/fastapi/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/opt/homebrew/Caskroom/miniconda/base/envs/fastapi/lib/python3.11/site-packages/uvicorn/server.py", line 78, in serve
    await self.startup(sockets=sockets)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/fastapi/lib/python3.11/site-packages/uvicorn/server.py", line 89, in startup
    await self.lifespan.startup()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/fastapi/lib/python3.11/site-packages/uvicorn/lifespan/on.py", line 49, in startup
    main_lifespan_task = loop.create_task(self.main())  # noqa: F841
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1431, in uvloop.loop.Loop.create_task
TypeError: task_factory() got an unexpected keyword argument 'context'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/fastapi/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/fastapi/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/fastapi/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/fastapi/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/fastapi/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/fastapi/lib/python3.11/site-packages/uvicorn/main.py", line 416, in main
    run(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/fastapi/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/fastapi/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/fastapi/lib/python3.11/asyncio/runners.py", line 189, in run
    with Runner(debug=debug) as runner:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/fastapi/lib/python3.11/asyncio/runners.py", line 63, in __exit__
    self.close()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/fastapi/lib/python3.11/asyncio/runners.py", line 72, in close
    loop.run_until_complete(loop.shutdown_asyncgens())
  File "uvloop/loop.pyx", line 1487, in uvloop.loop.Loop.run_until_complete
  File "/opt/homebrew/Caskroom/miniconda/base/envs/fastapi/lib/python3.11/asyncio/tasks.py", line 649, in ensure_future
    return _ensure_future(coro_or_future, loop=loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/fastapi/lib/python3.11/asyncio/tasks.py", line 670, in _ensure_future
    return loop.create_task(coro_or_future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1431, in uvloop.loop.Loop.create_task
TypeError: task_factory() got an unexpected keyword argument 'context'
sys:1: RuntimeWarning: coroutine 'Loop.shutdown_asyncgens' was never awaited
```
## My Command
`uvicorn fastapi_test:app --port=2000`

**Comment by JoJoJoJoJoJoJo** [comment]
I also found an issue here which looks like similar

getsentry/sentry-python#1993

**Comment by jj22ee** [comment]
I wasn't able to reproduce the issue with your sample code, at least on Python 3.11.7. I provided the dependency versions I used in a Linux environment:
```
yyyyyyyyyy % pip list | grep -e aws-xray-sdk -e fastapi -e uvicorn
aws-xray-sdk                  2.12.1
fastapi                       0.108.0
uvicorn                       0.25.0

(24-01-10 23:07:43) <0> [~/temp]  
yyyyyyyyyy %% uvicorn --version                                    
Running uvicorn 0.25.0 with CPython 3.11.7 on Linux

(24-01-10 23:07:55) <0> [~/temp]  
yyyyyyyyyy % uvicorn test:app --port=2000                         
INFO:     Started server process [129701]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:2000/ (Press CTRL+C to quit)
```

However, in your sample code I also noticed this syntax error:
>xray_recorder.configure('app', context=AsyncContext())

I think you must have wanted:
>xray_recorder.configure(service='app', context=AsyncContext())

Does the error still persist if you fix the syntax error and use the same dependency versions?

**Comment by JoJoJoJoJoJoJo** [comment]
It still persists after I fixed the syntax error.
However, when I create a new conda environment and install the same dependent packages, the error can't be reproduced. 🤣 
Anyway it works fine now, thank you a lot for your attention.
